services:
  n8n:
    image: 'n8nio/n8n:1.108.1'
    container_name: n8n
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.SEU_DOMINIO`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.services.n8n.loadbalancer.server.scheme=http
      - traefik.http.routers.n8n.priority=50
    env_file:
      - .env
    networks:
      - proxy
      - n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files
    depends_on:
      postgres-n8n:
        condition: service_healthy
      redis-n8n:
        condition: service_started

  n8n-worker:
    image: 'n8nio/n8n:1.108.1'
    container_name: n8n-worker
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n
    depends_on:
      postgres-n8n:
        condition: service_healthy
      redis-n8n:
        condition: service_started
      n8n:
        condition: service_started
    env_file:
      - .env
    command: worker

  n8n-webhook:
    image: 'n8nio/n8n:1.108.1'
    container_name: n8n-webhook
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n-webhook.rule=Host(`n8n.SEU_DOMINIO`) && PathPrefix(`/webhook`)
      - traefik.http.routers.n8n-webhook.entrypoints=websecure
      - traefik.http.routers.n8n-webhook.tls.certresolver=le
      - traefik.http.routers.n8n-webhook.priority=100
      - traefik.http.services.n8n-webhook.loadbalancer.server.port=5678
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres-n8n:
        condition: service_healthy
      redis-n8n:
        condition: service_started
      n8n:
        condition: service_started
    env_file:
      - .env
    networks:
      - proxy
      - n8n
    command: webhook

  postgres-n8n:
    image: ankane/pgvector
    container_name: postgres-n8n
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=n8n
    networks:
      - n8n
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-n8n:
    image: redis:alpine
    container_name: redis-n8n
    restart: always
    networks:
      - n8n
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  n8n:
    driver: bridge
  proxy:
    external: true