deploy:
	docker-compose down -v && docker-compose up -d
down:
	docker-compose down
up:
	docker-compose up -d
downv:
	docker-compose down -v
ps:
	docker-compose ps
stop:
	docker-compose stop
start:
	docker-compose start
restart:
	docker-compose restart
	